config/routes.rb
Beerance::Application.routes.draw do  
  devise_for :users, :path => "sessions", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register' }
  
  # API
  scope "/api/v1/" do 
    get 'bars/:id' => 'api_v1#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v1#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v1#specials_near_zip', :defaults => { :format => 'json' }
  end

  scope "/api/v2/" do 
    get 'bars/:id' => 'api_v2#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v2#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v2#specials_near_zip', :defaults => { :format => 'json' }
  end

  # Meta tags
  get '/admin/meta-tags/edit' => 'meta_tags#edit', as: 'edit_meta_tag'
  resources :meta_tags

  # Billing  
  get  '/billing'                           => 'billing#index', as: 'billing_overview'
  get  '/billing/bars/:id'                  => 'billing#show', as: 'show_billing'
  get  '/billing/change-plan/:id'           => 'billing#edit_plan', as: 'edit_plan'
  get  '/billing/change-card/:id'           => 'billing#edit_card', as: 'edit_card'
  get  '/billing/bars/:id/invoices'         => 'billing#invoices', as: 'invoices'
  get  '/billing/bars/invoices-details/:id' => 'billing#show_invoice', as: 'show_invoice'
  post '/billing/update-plan/:id'           => 'billing#update_plan', as: 'update_plan', via: [:get, :post]
  post '/billing/update-card/:id'           => 'billing#update_card', as: 'update_card', via: [:get, :post]
  get  '/cancel-subscription/:id'           => 'billing#cancel_subscription', as: 'cancel_subscription'

  # Password resests
  get '/send-password-reset' => 'password_resets#new'
  resources :password_resets, path: 'password-resets'

  # Home pages
  get  '/tos'            => 'home#tos', as: 'tos'
  get  '/about'          => 'home#about', as: 'about'
  get  '/legal'          => 'home#legal', as: 'legal'
  get  '/support'        => 'home#support', as: 'support'
  get  '/pricing'        => 'home#pricing', as: 'pricing'
  get  '/privacy'        => 'home#privacy', as: 'privacy'
  get  '/sign-up'        => 'home#signup', as: 'signup'
  get  '/get-the-app'    => 'home#get_the_app', as: 'get_the_app'
  get  '/how-it-works'   => 'home#how_it_works', as: 'how_it_works'
  get  '/recent-updates' => 'home#recent_updates', as: 'recent_updates'
  get  '/for-bar-owners' => 'home#for_bar_owners', as: 'for_bar_owners'  
  get  '/map/bar-info/:id' => 'home#bar_info', as: 'bar_info'
  post '/new-sign-up'    => 'home#new_signup', as: 'new_signup', via: [:get, :post]
  match  '/specials'           => 'home#map', via: :all, as: 'map'  

  # Feedback
  get  '/feedback'       => 'feedback#index', as: 'feedback'
  post '/send-feedback'  => 'feedback#send_feedback', as: 'send_feedback', via: [:get, :post]
  
  # Users
  resources :users  
  get   '/account-details'                => 'users#show', :as => 'account_details'    
  get   '/my-beerances/current-specials'  => 'users#current_specials', as: 'current_specials'
  get   '/my-beerances/archived-specials' => 'users#archived_specials', as: 'archived_specials'  
  get   '/my-beerances'                   => 'users#profile', as: 'profile'
  get   '/my-beerances/archived'          => 'users#profile', as: 'profile_archive'
  
  # Bars
  resources :bars
  
  # Bar Specials
  resources :bar_specials, except: [:new], path: 'bar-specials'
  get   '/end-beerance/:id'      => 'bar_specials#toggle_beerance', as: 'end_beerance'
  get   '/reactive-beerance/:id' => 'bar_specials#toggle_beerance', as: 'reactivate_beerance'
  get 'bar-specials'           => 'bar_specials#index', as: 'bar_specials_index'
  get 'bar-specials/new'       => 'bar_specials#new', as: 'new_bar_special'

  # Admin panel
  scope "/admin/" do 
    get   '/'                   => 'admin#index', as: 'admin'
    get   '/test-email'         => 'admin#test_email', as: 'test_email'
    get   '/news-subscriptions' => 'admin#news_subscriptions', as: 'news_subscriptions'
    match '/users'              => 'admin#user_index', as: 'admin_users', via: [:get, :post]
    match '/users/:id'          => 'admin#user_show', as: 'admin_user', via: [:get, :post]
    match '/make-admin'         => 'users#make_admin', as: 'make_admin', via: [:get, :post]
    match '/remove-admin'       => 'users#remove_admin', as: 'remove_admin', via: [:get, :post]
    match '/impersonate'        => 'admin#impersonate', as: 'impersonate', via: [:get, :post]
    match '/feedback'           => 'admin#feedback', as: 'admin_feedback', via: [:get, :post]
  end
  
  # Root Path
  root to: 'home#index'  
end

app/views/admin/feedback.html.erb
<div class="row heading">
  <div class="large-12 columns">
    <%= image_tag "pin.png" %><h2>List of Feedback</h2>
  </div>
</div>

<div class="beerance_list">
  <div class="row purple_grad">
    <div class="large-4 columns">
      Category
    </div>
    <div class="large-3 columns">
      Email
    </div>
    <div class="large-5 columns">
      Comments
    </div>
  </div>
  <% @feedbacks.each.each do |f| %>
    <div class="row">
      <div class="large-4 columns">
        <%= f.category %>
      </div>
      <div class="large-3 columns">
        <%= link_to f.user.email, admin_user_path(f.user) %>
      </div>
      <div class="large-5 columns">
        <%= f.comment %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/index.html.erb
<h2>BeeranceApp.com Admin Portal</h2>
<h4 class="subheader">Here you can manage setting about the application and users</h4>
<hr />

<p style="color:red">
  THIS PORTAL AND THE INFORMATION IN IT ARE PROVIDED IN CONFIDENCE, FOR THE SOLE PURPOSE OF CUSTOMER SERVICE, AND ANY CUSTOMER INFORMATION MAY NOT BE DISCLOSED TO ANY THIRD PARTY OR USED FOR ANY OTHER PURPOSE.
</p>

app/views/admin/news_subscriptions.html.erb
<h3>List of News Subscriptions</h3>

<ul>
  <% MailChimpList.all.each do |l| %>
    <li>List ID: <%= l.id %> - List Name: <%= l.name %></li>
  <% end %>
</ul>

<div class="large-6 columns">
<ul>
  <h3>Drinkers</h3>
  <% @drinker_news_subscriptions.each do |ns| %>
    <% unless ns.subscriber_email.blank? %>
      <li><%= ns.subscriber_email %></li>
    <% end %>
  <% end %>
</ul>
</div>
<div class="large-6 columns">
<ul>
  <h3>Owners</h3>
  <% @owner_news_subscriptions.each do |ns| %>
    <% unless ns.subscriber_email.blank? %>
      <li><%= ns.subscriber_email %></li>
    <% end %>
  <% end %>
</ul>
</div>

app/views/admin/user_index.html.erb
<style>
tbody tr:hover {background: #F7E2B8;}
</style>
<h3>List of Users</h3>
<table style="width: 100%;">
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin?</th>
      <th>Bars</th>
      <th>Actions</th>
      <th>Danger Zone!</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |u| %>
    <% unless u.name.blank? %>
    <tr>
      <td><%= link_to u.email, admin_user_path(u) %></td>
      <td><%= u.admin? ? 'yes' : '' %></td>
      <td><%= u.bars.count %></td>
      <td>
        <%= link_to "Edit", edit_user_path(u) %>
      </td>
      <td>
        <% if u.id == current_user.id %>
          This is YOU!
        <% else %>
          <%= link_to "Delete", user_path(u), method: 'delete', data: {confirm: "Are you sure?"} %> | 
          <% if u.admin? %>
            <%= link_to "Remove Admin", remove_admin_path(id: u.id) %>
          <% else %>
            <%= link_to "Make Admin", make_admin_path(id: u.id) %>
          <% end %>
        <% end %>
        |
        <%= link_to_if (%w(dh@dillonhafer.com cnagy@boondockwalker.com).include? current_user.email), "Impersonate", impersonate_path(id: u.id) %>
      </td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/admin/user_show.html.erb
<h2>Records for: <%= @user.email %></h2>

<div class="row heading">
    <div class="large-9 columns">
        <img alt="Beerance_baricon" src="/assets/beerance_baricon.png"><h2>Bars</h2>
    </div>
  <div class="large-3 columns">
  </div>
</div>

<div class="content bar-list">
  <div class="large-12 columns">
    <% @user.bars.each do |bar| %>
      <div id="bar-<%= bar.id %>" class="row" style="border-bottom: 1px solid #3e130d; margin-bottom: 20px;">
          <div class="row">
            <div class="large-12 columns user-info" style ="padding-bottom:0;">
              <h2><%= bar.name %>
                <small>
                  <%= link_to "edit", edit_bar_path(bar) %>
              </small>
            </h2>
          </div>
        </div>
        <div class="row">
            <div class="large-6 columns user_info" style="padding-left:35px;">
            <span><%= bar.address %></span>
              <% unless bar.address_2.blank? %>
            <span><%= bar.bar_addr2 %></span>
              <% end %>
            <span><%= bar.city %>, <%= bar.state %></span>
            <span><%= bar.zip %></span>
            <span><%= link_to bar.nice_url, "#{bar.nice_url}", target: :_blank %></span>
          </div>
          <div class="large-6 columns user_info">
            <span>Plan: <%= format_plan bar %></span>
            <span><%= number_to_phone bar.phone, area_code: true %></span>
            <span><%= link_to "View Invoices", invoices_path(bar.id) %></span>            
          </div>
        </div>
        </div>   
        <% end %>    
      </div>
  </div>