config/routes.rb
Beerance::Application.routes.draw do  
  devise_for :users, :path => "sessions", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register' }
  
  # API
  scope "/api/v1/" do 
    get 'bars/:id' => 'api_v1#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v1#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v1#specials_near_zip', :defaults => { :format => 'json' }
  end

  scope "/api/v2/" do 
    get 'bars/:id' => 'api_v2#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v2#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v2#specials_near_zip', :defaults => { :format => 'json' }
  end

  # Meta tags
  get '/admin/meta-tags/edit' => 'meta_tags#edit', as: 'edit_meta_tag'
  resources :meta_tags

  # Billing  
  get  '/billing'                           => 'billing#index', as: 'billing_overview'
  get  '/billing/bars/:id'                  => 'billing#show', as: 'show_billing'
  get  '/billing/change-plan/:id'           => 'billing#edit_plan', as: 'edit_plan'
  get  '/billing/change-card/:id'           => 'billing#edit_card', as: 'edit_card'
  get  '/billing/bars/:id/invoices'         => 'billing#invoices', as: 'invoices'
  get  '/billing/bars/invoices-details/:id' => 'billing#show_invoice', as: 'show_invoice'
  post '/billing/update-plan/:id'           => 'billing#update_plan', as: 'update_plan', via: [:get, :post]
  post '/billing/update-card/:id'           => 'billing#update_card', as: 'update_card', via: [:get, :post]
  get  '/cancel-subscription/:id'           => 'billing#cancel_subscription', as: 'cancel_subscription'

  # Password resests
  get '/send-password-reset' => 'password_resets#new'
  resources :password_resets, path: 'password-resets'

  # Home pages
  get  '/tos'            => 'home#tos', as: 'tos'
  get  '/about'          => 'home#about', as: 'about'
  get  '/legal'          => 'home#legal', as: 'legal'
  get  '/support'        => 'home#support', as: 'support'
  get  '/pricing'        => 'home#pricing', as: 'pricing'
  get  '/privacy'        => 'home#privacy', as: 'privacy'
  get  '/sign-up'        => 'home#signup', as: 'signup'
  get  '/get-the-app'    => 'home#get_the_app', as: 'get_the_app'
  get  '/how-it-works'   => 'home#how_it_works', as: 'how_it_works'
  get  '/recent-updates' => 'home#recent_updates', as: 'recent_updates'
  get  '/for-bar-owners' => 'home#for_bar_owners', as: 'for_bar_owners'  
  get  '/map/bar-info/:id' => 'home#bar_info', as: 'bar_info'
  post '/new-sign-up'    => 'home#new_signup', as: 'new_signup', via: [:get, :post]
  match  '/specials'           => 'home#map', via: :all, as: 'map'  

  # Feedback
  get  '/feedback'       => 'feedback#index', as: 'feedback'
  post '/send-feedback'  => 'feedback#send_feedback', as: 'send_feedback', via: [:get, :post]
  
  # Users
  resources :users  
  get   '/account-details'                => 'users#show', :as => 'account_details'    
  get   '/my-beerances/current-specials'  => 'users#current_specials', as: 'current_specials'
  get   '/my-beerances/archived-specials' => 'users#archived_specials', as: 'archived_specials'  
  get   '/my-beerances'                   => 'users#profile', as: 'profile'
  get   '/my-beerances/archived'          => 'users#profile', as: 'profile_archive'
  
  # Bars
  resources :bars
  
  # Bar Specials
  resources :bar_specials, except: [:new], path: 'bar-specials'
  get   '/end-beerance/:id'      => 'bar_specials#toggle_beerance', as: 'end_beerance'
  get   '/reactive-beerance/:id' => 'bar_specials#toggle_beerance', as: 'reactivate_beerance'
  get 'bar-specials'           => 'bar_specials#index', as: 'bar_specials_index'
  get 'bar-specials/new'       => 'bar_specials#new', as: 'new_bar_special'

  # Admin panel
  scope "/admin/" do 
    get   '/'                   => 'admin#index', as: 'admin'
    get   '/test-email'         => 'admin#test_email', as: 'test_email'
    get   '/news-subscriptions' => 'admin#news_subscriptions', as: 'news_subscriptions'
    match '/users'              => 'admin#user_index', as: 'admin_users', via: [:get, :post]
    match '/users/:id'          => 'admin#user_show', as: 'admin_user', via: [:get, :post]
    match '/make-admin'         => 'users#make_admin', as: 'make_admin', via: [:get, :post]
    match '/remove-admin'       => 'users#remove_admin', as: 'remove_admin', via: [:get, :post]
    match '/impersonate'        => 'admin#impersonate', as: 'impersonate', via: [:get, :post]
    match '/feedback'           => 'admin#feedback', as: 'admin_feedback', via: [:get, :post]
  end
  
  # Root Path
  root to: 'home#index'  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :phone
  validates_presence_of :password, on: :create
  validates_confirmation_of :password, on: :create

  has_many :bars
  has_many :feedbacks
  has_many :bar_specials, through: :bars
  
  default_scope { order('users.created_at ASC') }
  
  def admin?() admin end
  def make_admin() update_attributes(admin: true) end  
  def remove_admin() update_attributes(admin: false) end
  def gary?() email.downcase == 'gcintron@rockyriverbrewco.com' end

  def self.current
    Thread.current[:user]
  end
  
  def self.current=(user)
    Thread.current[:user] = user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user
  before_filter :require_admin, only: %w{index admin_show destroy make_admin remove_admin}
  before_filter :new_bar_special, only: %w{profile current_specials}

  def index
    @users = User.all
  end

  def admin_show
    @user = User.find params[:id]
    @customer = Stripe::Customer.retrieve @user.stripe_customer_id
  end

  def show        
  end

  def profile    
    redirect_to new_bar_path if current_user.bars.blank?
  end

# Basic CRUD actions
  def edit
    @user = User.find params[:id]
    render layout: 'account_details'
  end

  def update    
    @user = User.find params[:id]    
    if @user.update_attributes(user_params)
      redirect_to account_details_path
    else
      render :edit
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to users_path
  end

# Admin Actions
  def make_admin
    user = User.find params[:id]
    user.make_admin
    redirect_to admin_users_path, notice: 'Updated User'
  end

  def remove_admin
    user = User.find params[:id]
    user.remove_admin
    redirect_to admin_users_path, notice: 'Updated User'
  end

# Before Filters
  def new_bar_special
    @bar_special = BarSpecial.new    
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def expiration_date_format(expiration_date)
    days_left = (expiration_date-Date.today).to_i
    days_left = days_left > 0 ? "<span style='color: green'>#{pluralize(days_left, 'day')}</span>" : "<span style='color:red'>Expired!</span>"
    "#{expiration_date.strftime("%A, %b %d, %Y")} (#{days_left})".html_safe
  end

  def has_a_bar?
    current_user.bars.count > 0
  end

  def my_bars(number)
    "My "+ pluralize(number, 'Bar').gsub(/[\d]/, '')
  end

  def current_subnav(path)
    case request.path_info
      when path
        'current'
      else
        ''
      end
  end
end

app/views/users/_archives.html.erb
<div class="row heading">
  <div class="large-9 columns">
    <%= image_tag "beerance_mugicon.png" %><h2>Archived Specials</h2>
  </div>  
</div>

<% if current_user.bar_specials.inactive.any? %>

<div class="beerance_list">
	<div class="row hide-for-small purple_grad">
		<div class="large-5 columns">
			Name
		</div>
		<div class="large-1 columns">
			Color
		</div>
		<div class="large-1 columns">
			Price
		</div>
		<div class="large-1 columns">
			Size
		</div>
		<div class="large-2 columns">
			Location
		</div>
		<div class="large-2 columns align-center">
			Reactivate
		</div>
	</div>
		
	<% current_user.bar_specials.inactive.each do |bs| %>
	<%= form_for bs, html: { data: {remote: true } } do |f| %>
	<%= f.hidden_field :bar_id %>

	<div class="row">
		<div class="large-5 columns">
			<span class="show-for-small">Name: </span>
			<%= f.label :description, bs.description %>
			<%= f.text_field :description, class: 'input-text hide' %>
		</div>
		<div class="large-1 columns color">
			<span class="show-for-small">Color: </span>
			  <%= f.label :description, beer_color_image(bs.beer_color) %>
			  <%= f.select :beer_color, [['Black', 0], ['Red', 1], ['Pale', 2], ['Amber', 3] ], {prompt: 'Color'}, class: 'input-text hide' %>
		</div>
		<div class="large-1 columns">
			<span class="show-for-small">Price: </span>
			<%= f.label :sale_price, number_to_currency(bs.sale_price) %>
			<%= f.text_field :sale_price, class: 'input-text hide' %>
		</div>
		<div class="large-1 columns">
			<span class="show-for-small">Size: </span>
			<%= f.label :beer_size, "#{bs.beer_size}oz" %>
			<%= f.select :beer_size, (4..32).map{|n|["#{n}oz",n]}.push(['64oz', 64]), {}, class: 'input-text hide' %>
		</div>
		<div class="large-3 columns">
			<span class="show-for-small">Location: </span>
			<%= bs.bar.name %>
		</div>
		<div class="large-1 columns align-center">
			<span class="show-for-small">Reactivate: </span>			
				<%= link_to "", reactivate_beerance_path(bs), class: 're-activate', data: {remote: true} %>
		</div>
	</div>
	<% end %> 
	<% end %> 
</div>

<% else %>
  <h3 style='text-align: center;'>You have no archived specials</h3>
<% end %>

<script>
	window.history.pushState({"html": $('.ajax-container').html(),"pageTitle":document.title},"", '/my-beerances/archived');
</script>

app/views/users/_current_specials.html.erb
<div class="row heading">
  <div class="large-9 columns">
    <%= image_tag "beerance_mugicon.png" %><h2>Current Specials</h2>
  </div>
  <div class="large-3 columns">
    <%= link_to "New Special", "javascript:void(0)", title: "New Special", class: 'button radius shadow new-special' %>
  </div>
</div>

<div class="beerance_list">
	<div class="row hide-for-small purple_grad">
		<div class="large-5 columns">
			Name
		</div>
		<div class="large-1 columns">
			Color
		</div>
		<div class="large-1 columns">
			Price
		</div>
		<div class="large-1 columns">
			Size
		</div>
		<div class="large-3 columns">
			Location
		</div>
		<div class="large-1 columns align-center">
			Remove
		</div>
	</div>
		<%= form_for @bar_special, html: { class: 'hide', data: {remote: true} } do |f| %>			
			<div class="row" id="newspecial">
				<div class="large-4 columns">
					<span class="show-for-small">Name: </span>					
					<%= f.text_field :description, placeholder: 'Name', class: 'input-text' %>
				</div>
				<div class="large-2 columns new-color">
					<span class="show-for-small">Color: </span>
					  <%= f.select :beer_color, [['Black', 0], ['Red', 1], ['Pale', 2], ['Amber', 3] ], prompt: 'Color' %>
				</div>
				<div class="large-1 columns">
					<span class="show-for-small">Price: </span>					
					<%= f.text_field :sale_price, placeholder: '3.99', class: 'input-text' %>
				</div>
				<div class="large-1 columns">
					<span class="show-for-small">Size: </span>					
					<%= f.select :beer_size, (4..32).map{ |n| ["#{n}oz",n] }.push(['64oz', 64]), prompt: 'Size' , class: 'input-text' %>
				</div>
				<div class="large-3 columns">
					<span class="show-for-small">Location: </span>
					<%= f.select :bar_id, current_user.bars.map {|b| [b.name, b.id] }, prompt: 'Choose A Bar'  %>
				</div>
				<div class="large-1 columns align-center">
					<%= f.submit "Add", class: 'small button radius shadow' %>
				</div>
			</div>
		<% end %> 
		
	<% current_user.bar_specials.active.each do |bs| %>
		<%= form_for bs, html: { data: {remote: true } } do |f| %>
			<%= f.hidden_field :bar_id %>
			<%= hidden_field_tag :current_page, true %>
			
			<div class="row">
				<div class="large-5 columns">
					<span class="show-for-small">Name*: </span>
					<%= f.label :description, bs.description %>
					<%= f.text_field :description, class: 'input-text hide' %>
				</div>
				<div class="large-1 columns color">
					<span class="show-for-small">Color: </span>
					  <%= f.label :description, beer_color_image(bs.beer_color) %>
					  <%= f.select :beer_color, [['Black', 0], ['Red', 1], ['Pale', 2], ['Amber', 3] ], {prompt: 'Color'}, class: 'input-text hide' %>
				</div>
				<div class="large-1 columns">
					<span class="show-for-small">Price*: </span>
					<%= f.label :sale_price, number_to_currency(bs.sale_price) %>
					<%= f.text_field :sale_price, class: 'input-text hide' %>
				</div>
				<div class="large-1 columns">
					<span class="show-for-small">Size*: </span>
					<%= f.label :beer_size, "#{bs.beer_size}oz" %>
					<%= f.select :beer_size, (4..32).map{ |n| ["#{n}oz",n] }.push(['64oz', 64]), {} , class: 'input-text hide' %>
				</div>
				<div class="large-3 columns">
					<span class="show-for-small">Location: </span>
					<%= bs.bar.name %>
				</div>
				<div class="large-1 columns align-center">
					<span class="show-for-small">Remove: </span>
					<%= link_to "", end_beerance_path(bs), class: 'remove', data: {remote: true} %>
				</div>
			</div>
		<% end %> 
	<% end %>

</div>

<% unless current_user.bar_specials.active.any? %>
	<br />
	<br />
	<h3 style='text-align: center;'>You have no current specials</h3>
<% end %>

<script>
window.history.pushState({"html": $('.ajax-container').html(),"pageTitle":document.title},"", '/my-beerances');
</script>

app/views/users/_specials.html.erb
<style>
div.row.inactive {
  background: #DDD !important;
  opacity: 0.9 !important;
  color: #444 !important;
}
div.row.inactive label {
  color: #444 !important;
}
div.row.inactive a.re-activate {

}
div.row.inactive img, div.row.inactive a.re-activate {
  filter: url(filters.svg#grayscale); /* Firefox 3.5+ */
  filter: gray; /* IE6-9 */
  -webkit-filter: grayscale(1); /* Google Chrome, Safari 6+ & Opera 15+ */
}
</style>
<div class="row heading">
  <div class="large-9 columns">
    <%= image_tag "beerance_mugicon.png" %><h2>Specials</h2>
  </div>
  <div class="large-3 columns">
    <%= link_to "New Special", "javascript:void(0)", title: "New Special", class: 'button radius shadow new-special' %>
  </div>
</div>

<div class="beerance_list">
  <div class="row hide-for-small purple_grad">
    <div class="large-5 columns">
      Name
    </div>
    <div class="large-1 columns">
      Color
    </div>
    <div class="large-1 columns">
      Price
    </div>
    <div class="large-1 columns">
      Size
    </div>
    <div class="large-3 columns">
      Location
    </div>
    <div class="large-1 columns align-center">
      Remove
    </div>
  </div>
    <%= form_for @bar_special, html: { class: 'hide', data: {remote: true} } do |f| %>      
      <div class="row" id="newspecial">
        <div class="large-4 columns">
          <span class="show-for-small">Name: </span>          
          <%= f.text_field :description, placeholder: 'Name', class: 'input-text' %>
        </div>
        <div class="large-2 columns new-color">
          <span class="show-for-small">Color: </span>
            <%= f.select :beer_color, [['Black', 0], ['Red', 1], ['Pale', 2], ['Amber', 3] ], prompt: 'Color' %>
        </div>
        <div class="large-1 columns">
          <span class="show-for-small">Price: </span>         
          <%= f.text_field :sale_price, placeholder: '3.99', class: 'input-text' %>
        </div>
        <div class="large-1 columns">
          <span class="show-for-small">Size: </span>          
          <%= f.select :beer_size, (4..32).map{ |n| ["#{n}oz",n] }.push(['64oz', 64]), prompt: 'Size' , class: 'input-text' %>
        </div>
        <div class="large-3 columns">
          <span class="show-for-small">Location: </span>
          <%= f.select :bar_id, current_user.bars.map {|b| [b.name, b.id] }, prompt: 'Choose A Bar'  %>
        </div>
        <div class="large-1 columns align-center">
          <%= f.submit "Add", class: 'small button radius shadow' %>
        </div>
      </div>
    <% end %> 
    
  <% current_user.bar_specials.order('expiration_date DESC, updated_at DESC').each do |bs| %>
    <%= form_for bs, html: { data: {remote: true } } do |f| %>
      <%= f.hidden_field :bar_id %>
      
      <div class="row<%= " inactive" unless bs.active? %>">
        <div class="large-5 columns">
          <span class="show-for-small">Name*: </span>
          <%= f.label :description, bs.description %>
          <%= f.text_field :description, class: 'input-text hide' %>
        </div>
        <div class="large-1 columns color">
          <span class="show-for-small">Color: </span>
            <%= f.label :description, beer_color_image(bs.beer_color) %>
            <%= f.select :beer_color, [['Black', 0], ['Red', 1], ['Pale', 2], ['Amber', 3] ], {prompt: 'Color'}, class: 'input-text hide' %>
        </div>
        <div class="large-1 columns">
          <span class="show-for-small">Price*: </span>
          <%= f.label :sale_price, number_to_currency(bs.sale_price) %>
          <%= f.text_field :sale_price, class: 'input-text hide' %>
        </div>
        <div class="large-1 columns">
          <span class="show-for-small">Size*: </span>
          <%= f.label :beer_size, "#{bs.beer_size}oz" %>
          <%= f.select :beer_size, (4..32).map{ |n| ["#{n}oz",n] }.push(['64oz', 64]), {} , class: 'input-text hide' %>
        </div>
        <div class="large-3 columns">
          <span class="show-for-small">Location: </span>
          <%= bs.bar.name %>
        </div>
        <div class="large-1 columns align-center">
          <% if bs.active? %>
            <span class="show-for-small">Remove: </span>
            <%= link_to "", end_beerance_path(bs), class: 'remove', data: {remote: true} %>
          <% else %>
             <span class="show-for-small">Reactivate: </span>      
            <%= link_to "", reactivate_beerance_path(bs), class: 're-activate', data: {remote: true} %>
          <% end %>
        </div>
      </div>
    <% end %> 
  <% end %>

</div>

<% unless current_user.bar_specials.any? %>
  <br />
  <br />
  <h3 style='text-align: center;'>You have no specials</h3>
<% end %>

app/views/users/admin_show.html.erb
<h2>Records for: <%= @user.username %></h2>
<div class='row'>  
    <div class="large-12 columns">
      <h2>Plan</h2>
      <% if @user.subscription %>
        <div class="row">
            <div class="large-3 columns user_info" style="text-align:center">  
                <%= image_tag 'beerance_mugicon.png' %><br />
                <span><%= @user.subscription.nice_name %></span>
            </div>
      <div class="large-9 columns user_info">  
              <span><%= number_to_currency @user.subscription.amount %></span>
        <span>Cost per month: <%= number_to_currency @user.subscription_plan.cost_per_month %></span>
        <span>He has <b><%= pluralize @user.subscription.days_remaining, 'day' %></b> remaining</span>
      </div>
    </div>
    <% else %>
    <p style="text-align:center;">
        It looks like you don't have a plan yet :(
      <%= link_to "Choose A Plan", '#', class: 'button radius' %>
    </p>
    <% end %>
    </div>
</div>

<div class='row'>  
    <div class="large-12 columns">
      <h2>Charges</h2>      
        <div class="row">
          <div class="large-12 columns user_info">
            <span><%= @customer.active_card.name %></span>
            <span><%= @customer.active_card.type %> - **** **** **** <%= @customer.active_card.last4 %></span>
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Paid?</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                <% @customer.charges.each do |charge| %>
                <tr>
                  <td><%= Time.at(charge.created) %></td>
                  <td><%= charge.paid %></td>
                  <td><%= number_to_currency charge.amount/100 %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>  
    </div>
</div>

app/views/users/archived_specials.js.erb
$('.ajax-container').html('<%= j render("archives") %>').fadeIn();
document.title = "Archived - Beerance App";

app/views/users/current_specials.js.erb
$('.ajax-container').hide().html('<%= j render("current_specials") %>').fadeIn();
document.title = "My Beerances - Beerance App";

app/views/users/edit.html.erb
<% title "Account Details - " %>

<div class="row heading">
    <div class="large-9 columns">
        <img alt="Beerance_baricon" src="/assets/beerance_kegicon.png"><h2>Update Account Information</h2>
    </div>
</div>

<%= form_for @user do |f| %>  
  <% if @user.errors.any? %>  
    <div class="error_messages">  
      <h4>Something isn't quite right...</h4>
      <ul>  
        <% for message in @user.errors.full_messages %>  
          <li><%= message.gsub('202 username', 'Email') %></li>  
        <% end %>  
      </ul>  
    </div>  
    <br />
  <% end %>  
  
    <%= f.label :email %><br />  
    <%= f.email_field :username %>  

    <%= f.label :owner_name, "Name" %><br />  
    <%= f.text_field :owner_name %>  

    <%= f.label :owner_phone, "Phone" %><br />  
    <%= f.phone_field :owner_phone %>  
  
  <p>
    <%= f.submit "Update Account Information", class: 'small button radius shadow' %>
    <%= link_to "Cancel", account_details_path, class: 'red small button radius' %> 
  </p>
<% end %>  

app/views/users/new.html.erb
<% title 'Register - ' %>

			<div class="row">
				<div class='large-12 columns'>					
					<div class="row heading">
				    <div class="large-9 columns">
			        <img alt="Beerance_baricon" src="/assets/beerance_baricon.png"><h2>Join Beerance</h2>
				    </div>
			    </div>
					<%= form_for @user do |f| %>
						<% if @user.errors.any? %>
							<div class="error_messages">
								<h4>Form is invalid</h4>
								<ul>
									<% for message in @user.errors.full_messages %>
									<li><%= message.gsub('202 username', 'Email') %></li>
									<% end %>
								</ul>
							</div>
						<% end %>
					<div class='large-4 columns'>
						<%= f.label :email %><br />
						<%= f.email_field :username, placeholder: 'master@jedi.com', class: 'required' %>
						<%= f.label :password %><br />
						<%= f.password_field :password, class: 'required' %>						
					</div>
					<div class='large-1 columns'></div>
					<div class='large-4 columns'>
						<%= f.label :owner_name, "Your Name" %><br />
						<%= f.text_field :owner_name, placeholder: 'Luke S. Walker', class: 'required' %>
						<%= f.label :owner_phone, "Business Phone Number" %><br />
						<%= f.phone_field :owner_phone, placeholder: '216-123-4567', class: 'required' %>
					</div>
					<div class='large-3 columns'></div>				
		
			<div class='row'>
				<div class='large-12 columns'>
					<label>
						<%= f.check_box :newsletter_subscription, checked: true %> Sign up for our newsletter
					</label>
				</div>
			</div>
			<div class='row'>
				<div class='large-12 columns'>
					<p>By clicking you agree to the <%= link_to "Terms of Service", tos_path %>, <%= link_to "Privacy", privacy_path %>, and <%= link_to "Refund policies", 'javascript:void(0)' %>.</p>
					<%= f.submit "Join Beerance", class: 'button radius shadow' %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
		

app/views/users/new.js.erb
$('.ajax-container').html('<%= j render("subscriptions") %>');
$('head').append(' <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month\'s subscription"
          data-amount="500"></script>')

app/views/users/profile.html.erb
<div class='large-12 columns'>
  <div class="row">
      <div class="large-12 columns">
          <div class='ajax-container'>
              <% title "My Beerances - " %>
              <%= render partial: 'specials' %>
            </div>          
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% title "Account Details - " %>

<div class='large-12 columns'>
  <div class="row">
      <div class="large-12 columns">
          <div class='ajax-container'>
              <div class="row heading">
                <div class="large-9 columns">
                  <%= image_tag "beerance_kegicon.png" %><h2><%= current_user.name %>'s Account</h2>
                </div>
              </div>

              <div class='row'>  
                  <div class="large-12 columns user_info">
                      <h2>Info</h2>
                      <span><b>Name:</b> <%= current_user.name %></span>
                      <span><b>Email:</b> <%= current_user.email %></span>
                      <span><b>Phone:</b> <%= number_to_phone current_user.phone, area_code: true %></span>                      
                      <span><%= link_to "Change Account Information or Password", edit_registration_path('user') %></span>
                  </div>
              </div>
              <div class='row'>  
                <div class="large-12 columns">
                      <h2>Statistics</h2>
                      <ul>
                        <li>You manage <%= pluralize current_user.bars.count, 'bar' %></li>
                        <li>You've posted <%= pluralize current_user.bar_specials.count, 'Beerance', 'Beerances' %></li>
                        <li>Member Since: <%= current_user.created_at.to_date.strftime("%-m/%-d/%Y") %></li>
                      </ul>
                  </div>
              </div>
              
            </div>          
        </div>
    </div>
</div>

app/views/users/toggle_beerance.js.erb
$('.alert-box.notice').remove();
$('#ajax_bar').before('<div class="alert-box notice"><%= flash[:notice] %></div>');

<% if @special.active? %>
  $('.ajax-container').html('<%= j render("archives") %>');
<% else %>
  $('.ajax-container').html('<%= j render("current_specials") %>');
<% end %>

$('#ajax_bar').fadeOut();
$('.alert-box.notice').hide().fadeIn('slow').delay(4000).fadeOut();