config/routes.rb
Beerance::Application.routes.draw do  
  devise_for :users, :path => "sessions", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register' }
  
  # API
  scope "/api/v1/" do 
    get 'bars/:id' => 'api_v1#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v1#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v1#specials_near_zip', :defaults => { :format => 'json' }
  end

  scope "/api/v2/" do 
    get 'bars/:id' => 'api_v2#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v2#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v2#specials_near_zip', :defaults => { :format => 'json' }
  end

  # Meta tags
  get '/admin/meta-tags/edit' => 'meta_tags#edit', as: 'edit_meta_tag'
  resources :meta_tags

  # Billing  
  get  '/billing'                           => 'billing#index', as: 'billing_overview'
  get  '/billing/bars/:id'                  => 'billing#show', as: 'show_billing'
  get  '/billing/change-plan/:id'           => 'billing#edit_plan', as: 'edit_plan'
  get  '/billing/change-card/:id'           => 'billing#edit_card', as: 'edit_card'
  get  '/billing/bars/:id/invoices'         => 'billing#invoices', as: 'invoices'
  get  '/billing/bars/invoices-details/:id' => 'billing#show_invoice', as: 'show_invoice'
  post '/billing/update-plan/:id'           => 'billing#update_plan', as: 'update_plan', via: [:get, :post]
  post '/billing/update-card/:id'           => 'billing#update_card', as: 'update_card', via: [:get, :post]
  get  '/cancel-subscription/:id'           => 'billing#cancel_subscription', as: 'cancel_subscription'

  # Password resests
  get '/send-password-reset' => 'password_resets#new'
  resources :password_resets, path: 'password-resets'

  # Home pages
  get  '/tos'            => 'home#tos', as: 'tos'
  get  '/about'          => 'home#about', as: 'about'
  get  '/legal'          => 'home#legal', as: 'legal'
  get  '/support'        => 'home#support', as: 'support'
  get  '/pricing'        => 'home#pricing', as: 'pricing'
  get  '/privacy'        => 'home#privacy', as: 'privacy'
  get  '/sign-up'        => 'home#signup', as: 'signup'
  get  '/get-the-app'    => 'home#get_the_app', as: 'get_the_app'
  get  '/how-it-works'   => 'home#how_it_works', as: 'how_it_works'
  get  '/recent-updates' => 'home#recent_updates', as: 'recent_updates'
  get  '/for-bar-owners' => 'home#for_bar_owners', as: 'for_bar_owners'  
  get  '/map/bar-info/:id' => 'home#bar_info', as: 'bar_info'
  post '/new-sign-up'    => 'home#new_signup', as: 'new_signup', via: [:get, :post]
  match  '/specials'           => 'home#map', via: :all, as: 'map'  

  # Feedback
  get  '/feedback'       => 'feedback#index', as: 'feedback'
  post '/send-feedback'  => 'feedback#send_feedback', as: 'send_feedback', via: [:get, :post]
  
  # Users
  resources :users  
  get   '/account-details'                => 'users#show', :as => 'account_details'    
  get   '/my-beerances/current-specials'  => 'users#current_specials', as: 'current_specials'
  get   '/my-beerances/archived-specials' => 'users#archived_specials', as: 'archived_specials'  
  get   '/my-beerances'                   => 'users#profile', as: 'profile'
  get   '/my-beerances/archived'          => 'users#profile', as: 'profile_archive'
  
  # Bars
  resources :bars
  
  # Bar Specials
  resources :bar_specials, except: [:new], path: 'bar-specials'
  get   '/end-beerance/:id'      => 'bar_specials#toggle_beerance', as: 'end_beerance'
  get   '/reactive-beerance/:id' => 'bar_specials#toggle_beerance', as: 'reactivate_beerance'
  get 'bar-specials'           => 'bar_specials#index', as: 'bar_specials_index'
  get 'bar-specials/new'       => 'bar_specials#new', as: 'new_bar_special'

  # Admin panel
  scope "/admin/" do 
    get   '/'                   => 'admin#index', as: 'admin'
    get   '/test-email'         => 'admin#test_email', as: 'test_email'
    get   '/news-subscriptions' => 'admin#news_subscriptions', as: 'news_subscriptions'
    match '/users'              => 'admin#user_index', as: 'admin_users', via: [:get, :post]
    match '/users/:id'          => 'admin#user_show', as: 'admin_user', via: [:get, :post]
    match '/make-admin'         => 'users#make_admin', as: 'make_admin', via: [:get, :post]
    match '/remove-admin'       => 'users#remove_admin', as: 'remove_admin', via: [:get, :post]
    match '/impersonate'        => 'admin#impersonate', as: 'impersonate', via: [:get, :post]
    match '/feedback'           => 'admin#feedback', as: 'admin_feedback', via: [:get, :post]
  end
  
  # Root Path
  root to: 'home#index'  
end

app/views/shared/_account_details_subnav.html.erb
<div class='subnav'>
  <div class='row'>
    <div class="large-12 columns">      
      <%= link_to "My Account", profile_path %>
      <%= link_to "My Bars", bars_path %>      
      <%= link_to "Account Details", account_details_path, class: 'current' %>
      <%= link_to "Billing", billing_overview_path %>
    </div>
  </div>
</div>

<div class='subnav show-for-small'>
  <ul class="side-nav">
    <li class="active"><%= link_to "Current Specials", current_specials_path, class: 'current', data: {remote: true} %></li>
    <li><%= link_to "Archive", archived_specials_path, data: {remote: true} %></li>
    <li><%= link_to "My Bars", bars_path, data: {remote: true} %></li>
  </ul>
</div>

app/views/shared/_admin_subnav.html.erb
<div class='subnav'>
  <div class='row'>
    <div class="large-12 columns">
      <%= link_to "Admin Panel", admin_path, class: is_current?('index') %>
      <%= link_to "User List", admin_users_path, class: are_current?(%w{user_index user_show}) %>
      <%= link_to "News Subscriptions", news_subscriptions_path, class: is_current?('news_subscriptions') %>
      <%= link_to "SEO", edit_meta_tag_path, class: is_current?('edit') %>
      <%= link_to "Feedback", admin_feedback_path, class: is_current?('admin_index') %>
    </div>
  </div>
</div>

app/views/shared/_bars_subnav.html.erb
<div class='subnav'>
  <div class='row'>
    <div class="large-12 columns">      
      <%= link_to "My Bars", bars_path, class: is_current?('index') %>
      <%= link_to "Add New Bar", new_bar_path, class: is_current?('new') %>
    </div>
  </div>
</div>

<div class='subnav show-for-small'>
  <ul class="side-nav">
    <li class="active"><%= link_to "Current Specials", profile_path %></li>
    <li><%= link_to "Archive", profile_path %></li>
    <li><%= link_to "My Bars", bars_path, class: 'current' %></li>
    <li><%= link_to "Account Details", profile_path %></li>
  </ul>
</div>

app/views/shared/_billing_subnav.html.erb
<div class='subnav'>
  <div class='row'>
    <div class="large-12 columns">
      <%= link_to "Billing", billing_overview_path, class: is_current?('index') %>      
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<% cache do %>
    <div class="footer_wrap">
      <div class="row">      
      <div class="large-12 columns">
        <footer id="footermain" class="container">
          <div>
            <!--
            <ul>
              <li><h2>Support:</h2></li>
              <li>FAQs</li>
              <li>Blog</li>
              <li>Twitter</li>
              <li>Email Us</li>
            </ul>
            -->
            <ul>
              <li><h2>Follow Us:</h2></li>
              <li><a href="https://www.facebook.com/BeeranceApp" target="_blank">Facebook</a></li>
              <li><a href="https://www.twitter.com/BeeranceApp" target="_blank">Twitter</a></li>
            </ul>
            <!--
            <ul>
              <li><h2>You Should Know:</h2></li>
              <li><%= link_to "Terms of Use", tos_path %></li>
              <li><%= link_to "Privacy Policy", privacy_path %></li>
              <li><%= link_to "Recent Updates", recent_updates_path, class: 'large-6' %></li>
            </ul>
            
            <span class="copy left"><%= link_to 'log in', new_user_session_path %></span>-->
            <span class="copy hide-for-small">© <%= Date.today.year %> Beerance Company LLC</span>
          </div>
          <div class="row spacing top bottom show-for-small">
            <span style="position: absolute; left: 25px; top: 93px;">© <%= Date.today.year %> Beerance Company LLC</span>
          </div>
        </footer>
      </div>
    </div>
  </div>

<div id="newsLetter" class="reveal-modal small orange_grad" style="">
  <h2>News Letter</h2>
  <p class="lead">Be the first to know! Sign up today to receive Beerance app release dates, news and information.</p>
    <%= form_for @news_subscription, url: new_signup_path do |f| %>               
      <%= f.hidden_field :subscriber_type, value: "bar_drinker" %>
      <%= f.email_field :subscriber_email, placeholder: 'drinker@example.com', class: 'required' %>
      <%= submit_tag "Sign up", class: 'orange button radius full-width' %>
    <% end %>
  <a class="close-reveal-modal" style='color:white'>&#215;</a>
</div>
<% end %>

app/views/shared/_head.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <style>input {display:inline-block !important;}</style><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <title><%= yield(:title) %>Beerance App</title>
  <meta charset="utf-8" />
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width" />  
  
  <!-- SEO Tags -->
  <%= meta_tags %>
    
  <link href="touch-icon-iphone.png" rel="apple-touch-icon" />
  <link href="touch-icon-ipad.png" rel="apple-touch-icon" sizes="72x72" />
  <link href="touch-icon-iphone4.png" rel="apple-touch-icon" sizes="114x114" />
  <link href="touch-icon-ipad3.png" rel="apple-touch-icon" sizes="144x144" />

  <!-- Included CSS Files -->
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700|Roboto+Slab:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", media: 'all' %>
  
  <!-- Included JS Files  -->
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>    
  
  <!-- External JS Files 
  <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
   -->
  <script src="https://js.stripe.com/v1/"></script>
  <%= yield(:head) %>
</head>

app/views/shared/_header.html.erb
<% if flash[:notice] %>
  <div class='alert-box notice'><%= flash[:notice] %></div>
<% end %>

<% if flash[:error] %>
  <div data-alert class='alert-box alert'>
    <%= flash[:error] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>


<% if flash[:alert] %>
  <div data-alert class='alert-box alert'>
    <%= flash[:alert] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

<% cache do %>
<div id="ajax_bar"><%= image_tag "ajax-loader.gif", height: 32, width: 32 %><br /><br />loading...</div>   

<div class="login hide orange_grad">
  <div class='row clearfix'>
    <%= form_for("user", url: user_session_path, html: {id: 'header_login'}) do |f| %>
      <div class='large-3 columns'>
        <%= f.label :email, 'Email',style: "font-family: 'Roboto Slab', serif !important;"  %>
        <%= f.email_field :email, id: 'header_user_email', class: 'required', tabIndex: 1 %>
        <label for='user_remember_me'><%= f.check_box :remember_me, tabIndex: 3 %> Remember me</label>
      </div>
      <div class='large-3 columns'>
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, id: 'header_user_password', class: 'required', tabIndex: 2 %>
      </div>
      <div class='large-6 columns'>
        <br /><br />
        
        <%= f.submit "Log In", class: 'button' %>
        <%= link_to "Forgot your password?", new_password_path('user') %>
      </div>
    <% end %>  
  </div>
</div>
<% end %>

<% cache([current_user]) do %>
<div class='contain-to-grid'>
  <nav class="top-bar">
    <section class="top-bar-section" id="menu">
      <a href="/" id="logo"></a>
  		<% if current_user %>  
  		  <ul class="right myaccountsmall">
  		    <li class="divider hide-for-small"></li>
  		    <li><%= link_to "My Account", profile_path %>  </li>
  		    <li class="divider hide-for-small"></li>
  		  </ul>
  		<% if current_user.admin? %>
  		  <ul class="right">
  		    <li class="divider hide-for-small"></li>
  		    <li><%= link_to "Admin Portal", admin_path %></li>
  		  </ul>
  		<% end %>
  		
  		<ul class="right usernamehead">
  		    <li class="divider hide-for-small"></li>
  		    <li>Hi, <%= current_user.name %><%= link_to "(Log out)", destroy_user_session_path, :method => :delete %></li>
  		</ul>
  		
  		<% else %>
  		  <ul class="right">
  		    <li class="divider hide-for-small"></li>
  		    <li><%= link_to "Register", new_registration_path(resource_name), id: 'register', title: "Register", class: 'whitelink' %></li>
  		    <li class="divider hide-for-small"></li>
  		  </ul>
  		  <ul class="right">
  		    <li class="divider hide-for-small"></li>
  		    <li><%= link_to "Log In", "#", id: 'login', title: "Log In", class: 'whitelink'%></li>
  		  </ul>
  		<% end %> 
    </section>
  </nav>
</div>
<% end %>

app/views/shared/_mobile_header.html.erb
<div id="ajax_bar"><%= image_tag "ajax-loader.gif", height: 32, width: 32 %><br /><br />loading...</div>

<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/" id="logo"></a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon menu-trigger"><a href="#"><span>Menu</span></a></li>
  </ul>
</nav>

<div id="menu" class='hide'>
  <%= yield(:menu) %>
</div>

app/views/shared/_subnav.html.erb
<div class='subnav'>
  <div class='row'>
    <div class="large-12 columns">      
      <%= link_to "Home", root_path, class: is_current?('index') %>
      <%#= link_to "Get the App", get_the_app_path, class: is_current?('get_the_app') %>
      <%= link_to "How It Works", how_it_works_path, class: is_current?('how_it_works') %>
      <%#= link_to "For Bar Owners", for_bar_owners_path, class: is_current?('for_bar_owners') %>
      <%= link_to "Pricing", pricing_path, class: is_current?('pricing') %>
      <%= link_to "View Specials Now", map_path, class: 'show-for-small hide-for-medium hide-for-large' %>
      <%#= link_to "Support", support_path, class: is_current?('support') %>
      <a href="#" data-reveal-id="newsLetter" id='newsLetterLink'>Newsletter</a>
      <% if current_user %>
        <%= link_to "Post Specials", profile_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user_subnav.html.erb
<script>
$('.subnav a[data-remote="true"]').on('click', function(e) {  
  $('.ajax-container').fadeOut()
  $('.subnav a').each( function() {
    $(this).removeClass('current');
    $(this).removeClass('active');
    $(this).removeAttr('disabled');
  });
  $(this).addClass('current');  
})
</script>

<div class='subnav'>
  <div class='row'>
    <div class="large-12 columns">    
      <%= link_to "Specials", profile_path, class: current_subnav('/my-beerances') unless current_user.bars.count == 0 %>
      <%= link_to "My Bars", bars_path, class: current_subnav(/\A\/bar.+/) %>      
      <%= link_to "Account Details", account_details_path, class: current_subnav('/account-details') %>
      <%= link_to "Feedback", feedback_path, class: current_subnav('/feedback') %>
    </div>
  </div>
</div>