config/routes.rb
Beerance::Application.routes.draw do  
  devise_for :users, :path => "sessions", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register' }
  
  # API
  scope "/api/v1/" do 
    get 'bars/:id' => 'api_v1#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v1#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v1#specials_near_zip', :defaults => { :format => 'json' }
  end

  scope "/api/v2/" do 
    get 'bars/:id' => 'api_v2#show_bar', :defaults => { :format => 'json' }
    get 'bars/:id/specials' => 'api_v2#show_specials', :defaults => { :format => 'json' }
    get 'specials/near/:miles/of/:zip' => 'api_v2#specials_near_zip', :defaults => { :format => 'json' }
  end

  # Meta tags
  get '/admin/meta-tags/edit' => 'meta_tags#edit', as: 'edit_meta_tag'
  resources :meta_tags

  # Billing  
  get  '/billing'                           => 'billing#index', as: 'billing_overview'
  get  '/billing/bars/:id'                  => 'billing#show', as: 'show_billing'
  get  '/billing/change-plan/:id'           => 'billing#edit_plan', as: 'edit_plan'
  get  '/billing/change-card/:id'           => 'billing#edit_card', as: 'edit_card'
  get  '/billing/bars/:id/invoices'         => 'billing#invoices', as: 'invoices'
  get  '/billing/bars/invoices-details/:id' => 'billing#show_invoice', as: 'show_invoice'
  post '/billing/update-plan/:id'           => 'billing#update_plan', as: 'update_plan', via: [:get, :post]
  post '/billing/update-card/:id'           => 'billing#update_card', as: 'update_card', via: [:get, :post]
  get  '/cancel-subscription/:id'           => 'billing#cancel_subscription', as: 'cancel_subscription'

  # Password resests
  get '/send-password-reset' => 'password_resets#new'
  resources :password_resets, path: 'password-resets'

  # Home pages
  get  '/tos'            => 'home#tos', as: 'tos'
  get  '/about'          => 'home#about', as: 'about'
  get  '/legal'          => 'home#legal', as: 'legal'
  get  '/support'        => 'home#support', as: 'support'
  get  '/pricing'        => 'home#pricing', as: 'pricing'
  get  '/privacy'        => 'home#privacy', as: 'privacy'
  get  '/sign-up'        => 'home#signup', as: 'signup'
  get  '/get-the-app'    => 'home#get_the_app', as: 'get_the_app'
  get  '/how-it-works'   => 'home#how_it_works', as: 'how_it_works'
  get  '/recent-updates' => 'home#recent_updates', as: 'recent_updates'
  get  '/for-bar-owners' => 'home#for_bar_owners', as: 'for_bar_owners'  
  get  '/map/bar-info/:id' => 'home#bar_info', as: 'bar_info'
  post '/new-sign-up'    => 'home#new_signup', as: 'new_signup', via: [:get, :post]
  match  '/specials'           => 'home#map', via: :all, as: 'map'  

  # Feedback
  get  '/feedback'       => 'feedback#index', as: 'feedback'
  post '/send-feedback'  => 'feedback#send_feedback', as: 'send_feedback', via: [:get, :post]
  
  # Users
  resources :users  
  get   '/account-details'                => 'users#show', :as => 'account_details'    
  get   '/my-beerances/current-specials'  => 'users#current_specials', as: 'current_specials'
  get   '/my-beerances/archived-specials' => 'users#archived_specials', as: 'archived_specials'  
  get   '/my-beerances'                   => 'users#profile', as: 'profile'
  get   '/my-beerances/archived'          => 'users#profile', as: 'profile_archive'
  
  # Bars
  resources :bars
  
  # Bar Specials
  resources :bar_specials, except: [:new], path: 'bar-specials'
  get   '/end-beerance/:id'      => 'bar_specials#toggle_beerance', as: 'end_beerance'
  get   '/reactive-beerance/:id' => 'bar_specials#toggle_beerance', as: 'reactivate_beerance'
  get 'bar-specials'           => 'bar_specials#index', as: 'bar_specials_index'
  get 'bar-specials/new'       => 'bar_specials#new', as: 'new_bar_special'

  # Admin panel
  scope "/admin/" do 
    get   '/'                   => 'admin#index', as: 'admin'
    get   '/test-email'         => 'admin#test_email', as: 'test_email'
    get   '/news-subscriptions' => 'admin#news_subscriptions', as: 'news_subscriptions'
    match '/users'              => 'admin#user_index', as: 'admin_users', via: [:get, :post]
    match '/users/:id'          => 'admin#user_show', as: 'admin_user', via: [:get, :post]
    match '/make-admin'         => 'users#make_admin', as: 'make_admin', via: [:get, :post]
    match '/remove-admin'       => 'users#remove_admin', as: 'remove_admin', via: [:get, :post]
    match '/impersonate'        => 'admin#impersonate', as: 'impersonate', via: [:get, :post]
    match '/feedback'           => 'admin#feedback', as: 'admin_feedback', via: [:get, :post]
  end
  
  # Root Path
  root to: 'home#index'  
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  before_filter :require_user

  layout 'users'
  def index 
    redirect_to new_bar_path if current_user.bars.blank?
  end

  def invoices
    @bar = find_current_users_bar params[:id]
  end

  def show
    @bar = find_current_users_bar params[:id]    
  end

  def show_invoice
    if current_user.admin? || Bar.find_by_stripe_customer_id(@invoice.customer).user_id == current_user.id
      @invoice = Stripe::Invoice.retrieve params[:id]
    else
      redirect_to log_out_path
    end
  end

  def update_plan
    @bar = find_current_users_bar params[:id]    
    plan = SubscriptionPlan.find(params[:subscription_plan_id])
    @bar.update_plan(plan) unless @bar.subscription_plan_id == plan.id
    redirect_to show_billing_path(@bar.id), notice: 'Updated plan'
  end

  def edit_plan
    @bar = find_current_users_bar params[:id]    
  end

  def edit_card
    @bar = find_current_users_bar params[:id]
  end

  def update_card
    @bar = find_current_users_bar params[:id]
    if @bar.update_card(params[:stripe_card_token])
      redirect_to show_billing_path(@bar.id), notice: 'Updated Card Info'
    else
      render 'edit_card'
    end
  end

  def cancel_subscription
    @bar = find_current_users_bar params[:id]
    @bar.cancel_subscription
    @bar.update_attributes subscription_plan_id: ''   
    redirect_to show_billing_path(@bar.id), notice: 'We are so sad to see you go :('
  end

  def find_current_users_bar(id)
    if current_user.admin?
      Bar.find(id)
    else
      current_user.bars.find(id)
    end
  end
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/views/billing/edit_card.html.erb
<% content_for :head do %>
<meta name="stripe-key" content="<%= STRIPE_PUBLIC_KEY %>" />
<% end %>

<% title "Change Card - " %>
<%= form_tag update_card_path(@bar.id), id: 'edit_card' do %>
  <%= hidden_field_tag :stripe_card_token %>
  <h2>Update card for: <%= @bar.name %></h2>
  <h5>Card Information:</h5>
  <div class="row">
    <div class='large-6 offset-by-6 columns'>    
      <%= label_tag :card_name, "Name on card" %>
      <%= text_field_tag :card_name, nil, name: nil, placeholder: 'Luke S Walker' %>
    </div>
  </div>
  <div class="row">
    <div class='large-6 columns'>
      <%= label_tag :address_line_1, "Address" %>
      <%= text_field_tag :address_line_1, nil,  name: nil, class: "input-text small" %><br />
      <%= text_field_tag :address_line_2, nil,  name: nil, class: "input-text small" %>
    </div>
  </div>
  <div class="row">
    <div class='large-2 columns'>
      <%= label_tag :address_city, "City" %>
      <%= text_field_tag :address_city, nil,  name: nil, class: "input-text small" %>
    </div>
    <div class='large-2 columns'>
      <%= label_tag :address_city, "State" %>
      <%= select_tag :address_state, options_for_select(states.map {|s| s}),  name: nil, class: "input-text small" %>
    </div>
    <div class='large-2 columns'>
      <%= label_tag :address_city, "Zip" %>
      <%= text_field_tag :address_zip, nil,  name: nil, class: "input-text small" %>
    </div>
    <div class='large-6 columns'></div>
  </div>
  <div class="row">
    <div class='large-4 columns'>    
      <%= label_tag :card_number %>
      <%= phone_field_tag :card_number, '', name: nil, placeholder: '', required: '' %>
    </div>
    <div class='large-2 columns'>
      <%= label_tag :card_code, "(CVV)" %>
      <%= phone_field_tag :card_code, nil,  name: nil, class: "input-text small", maxlength: 4, placeholder: '000' %>
    </div>
    <div class='large-6 columns'></div>
  </div>
  <div class='row'>
    <div class="form-field">
      <div class='large-5 columns'>
        <%= label_tag :card_month, "Expiration Date" %><br />
        <%= select_month nil, {add_month_numbers: true}, {name: nil, id: 'card_month'} %>
        <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: 'card_year'} %>
      </div>
      <div class='large-7 columns'></div>
    </div>
  </div>

  <p id="stripe_error"></p>
  <%= submit_tag "Update Card Info", class: 'button radius shadow' %>
  <%= link_to "Cancel", billing_overview_path, class: 'red button radius shadow' %>
<% end %>

app/views/billing/edit_plan.html.erb
<h2>Change Your Plan</h2>
<br />
<%= form_tag update_plan_path(@bar.id) do %>
  <div class="row">
    <% SubscriptionPlan.order("amount").each do |p| %>
    <div class="large-4 columns">
      <article>
        <label class="amount plan-box <%= 'active' if @bar.subscription_plan_id == p.id %>">
          <%= "<br />Current Plan".html_safe if @bar.subscription_plan_id == p.id %>
          <h5><%= p.friendly_name %></h5>
          <%= radio_button_tag :subscription_plan_id, p.id, (@bar.subscription_plan_id == p.id) %>
          <%= image_tag p.image %><br />
          <span><%= number_to_currency p.amount/100 %></span>
        </label>
      </article>
    </div>
    <% end %>
  </div>

  <%= submit_tag "Change Plan", class: 'button radius shadow', data: {confirm: "Do you really want to change your plan?"} %>
  <%= link_to "Cancel", billing_overview_path, class: 'red button radius shadow' %>
<% end %>

<ul>
  <li>Changing your plan charges your card immediately.</li>
  <li>Changing your plan during your trial period will end your free trial.</li>
  <li>If you downgrade a plan, we will prorate the amount of the new plan.</li>
</ul>

app/views/billing/index.html.erb
<% title "Billing - " %>

<h2>Your Bars</h2>
<p>Manage the billing information and plan of your bars</p>
	<ul>
		<% current_user.bars.each do |bar| %>
  	<li><%= bar.name %> | <%= link_to "Details", show_billing_path(bar.id) %> | <%= link_to "Invoices", invoices_path(bar.id) %></li>
  	<% end %>
	</ul>

app/views/billing/invoices.html.erb
<style>
tr.hide {
  background: #DDD !important;
  border-bottom: 1px solid #AAA;
}
tr.hide:last-child {
  border-bottom: none;  
}

tbody tr:hover {background: #F7E2B8;}

</style>

<% title "Invoices - " %>

<h2>Invoices</h2>

<table style="width:100%;">
  <thead>
    <tr>
      <th>Invoice Date</th>
      <th>Period Start Date</th>
      <th>Period End Date</th>
      <th>Subtotal</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>
  </tbody>
  <% @bar.stripe_customer.invoices.each do |i| %>
    <tr>
      <td><%= Time.at(i.date).strftime("%B %d, %Y") %></td>
      <td><%= Time.at(i.period_start).strftime("%B %d, %Y") %></td>
      <td><%= Time.at(i.period_end).strftime("%B %d, %Y") %></td>
      <td><%= number_to_currency i.subtotal/100.to_f %></td>
      <td><%= number_to_currency i.total/100.to_f %></td>
      <td><%= link_to "details", show_invoice_path(id: i.id) %></td>
    </tr>    
  <% end %>
  </tbody>
</table>

app/views/billing/show.html.erb
<% title "Billing - " %>

<div class='row'>  
    <div class="large-12 columns">
    <h2>Plan for <%= @bar.name %></h2>
<% unless @bar.active_subscription? %>
<p class="centered" style="text-align:center"><br /><br /><br />You don't have an active subscription<br /><br /><%= link_to "Renew subscription", edit_plan_path(@bar.id), class: 'button radius shadow' %></p>
</div>
</div>
<% else %>
      <div class="row">
        <div class="large-3 columns user_info" style="text-align:center;padding-top: 29px;">  
            <%= image_tag 'beerance_mugicon.png' %><br />
            <span><%= @bar.subscription.nice_name %> </span>                
            <span><%= link_to "Change My Plan", edit_plan_path(@bar.id) %></span>
            <span><%= link_to_if !@bar.subscription.canceled?, "Cancel My Plan", cancel_subscription_path(@bar.id), data: {confirm: "Are you sure you would like to cancel your plan?"} %></span>
        </div>
        <div class="large-9 columns user_info">
          <span>Status: <%= @bar.subscription.status.capitalize %></span>
          <span><%= number_to_currency @bar.subscription.amount %></span>
          <span>Cost per month: <%= number_to_currency @bar.subscription_plan.cost_per_month %></span>
          <span>You have <b><%= pluralize @bar.subscription.days_remaining, 'day' %></b> remaining</span>
          <span>Ends on <b><%= @bar.subscription.end_date.strftime("%B %d, %Y") %></b></span>
          <% if @bar.subscription.canceled? %>
              <span style="font-size: 12px;padding: 0 0 0 10px; color: red"><em>Your plan was canceled on <%= @bar.subscription.canceled_at.strftime("%B %d, %Y") %>, and will not renew.</em></span>
          <% else %>
            <span style="font-size: 12px;padding: 0 0 0 10px;"><em>Your plan is set to auto renew for another <%= @bar.subscription_plan.length_in_months %> months</em></span>
          <% end %>
        </div>
      </div>    
    </div>
</div>

<div class='row'>  
    <div class="large-12 columns">
      <h2>Payment Info</h2>      
        <div class="row">
          <div class="large-12 columns user_info">
            <span>Name: <%= @bar.stripe_customer.cards.first.name %></span>
            <span><%= @bar.stripe_customer.cards.first.type %> - **** **** **** <%= @bar.stripe_customer.cards.first.last4 %></span>
            <span><%= link_to "Update Payment Info", edit_card_path(@bar.id), class: 'small orange button radius' %></span>
          </div>
        </div>    
    </div>
</div>
<% end %>

app/views/billing/show_invoice.html.erb
<style>
table {border:none;}

tr.total {
  background: none !important;
  border: none;
}
tr.total td:first-child { background: #E7E2B7 !important; border: none !important; }
tr.total td {
  background: #E7E2B7 !important;
}
tr.total td:last-child {
  background: #DDD !important;
}
</style>

<% title "Invoices - " %>

<h2>Invoice for <%= Time.at(@invoice.date).strftime("%B %d, %Y") %></h2>

<table>
  <thead>
    <tr>
      <th>Invoice Date:</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th><%= Time.at(@invoice.date).strftime("%B %d, %Y") %></th>
    </tr>
  </thead>
  </tbody>      
    <% @invoice.lines.each do |l| %>      
      <tr>
        <td colspan="4"><%= l.type %></td>
        <td><%= l.description %></td>
        <td><%= number_to_currency l.amount/100.to_f %></td>
      </tr>
    <% end %>
    <tr class='total'>
      <td colspan="4"></td>
      <td align="right">Subtotal:</td>
      <td><%= number_to_currency @invoice.subtotal/100.to_f %></td>
    </tr>
    <tr class='total'>
      <td colspan="4"></td>
      <td align="right">Total:</td>
      <td><%= number_to_currency @invoice.total/100.to_f %></td>
    </tr>
  </tbody>
</table>